### ISSUE TITLE
INDICES OUT OF DATA BOUNDS while simplifing an onnx model of mobilebnetv2ssd

### ISSUE THREAD

**Issue by ztianlin** [onnxsim/onnxsim#43]
Hi, I got this following error when executing the simplification. The .onnx model has been sent to your email. Can you share some solutions or ideas with it? Thx.
*************************************************
root@5277c7e46d46:/home/SSD_Lite# python -m onnxsim mobilenetv2ssd.onnx mobilenetv2ssd-sim.onnx
Simplifying...
2020-02-12 09:22:51.490512832 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Gather node. Name:'' Status Message: indices element out of data bounds, idx=94386739683648 must be within the inclusive range [-3234,3233]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/onnxsim/__main__.py", line 42, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/onnxsim/__main__.py", line 31, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, input_shapes=input_shapes)
  File "/opt/conda/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 303, in simplify
    res = forward_all(model, input_shapes=input_shapes)
  File "/opt/conda/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 158, in forward_all
    res = forward(model, input_shapes=input_shapes)
  File "/opt/conda/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 149, in forward
    res = OrderedDict(zip(outputs, sess.run(outputs, inputs, run_options=run_options)))
  File "/opt/conda/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'' Status Message: indices element out of data bounds, idx=94386739683648 must be within the inclusive range [-3234,3233]

**Comment by daquexian** [comment]
Thanks for your issue!

I believe there are some errors in the model. The gather node does have some indices whose values are like 94386739683648. Could you please upgrade your pytorch, export the onnx model once more and test it with onnxsim?

**Comment by take-cheeze** [comment]
No response so closing
